# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ddang/library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ddang/library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ddang/library/CMakeFiles /home/ddang/library/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ddang/library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyev

# Build rule for target.
tinyev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyev
.PHONY : tinyev

# fast build rule for target.
tinyev/fast:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/build
.PHONY : tinyev/fast

# target to build an object file
Acceptor.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Acceptor.o
.PHONY : Acceptor.o

# target to preprocess a source file
Acceptor.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Acceptor.i
.PHONY : Acceptor.i

# target to generate assembly for a file
Acceptor.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Acceptor.s
.PHONY : Acceptor.s

# target to build an object file
Buffer.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Buffer.o
.PHONY : Buffer.o

# target to preprocess a source file
Buffer.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Buffer.i
.PHONY : Buffer.i

# target to generate assembly for a file
Buffer.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Buffer.s
.PHONY : Buffer.s

# target to build an object file
Channel.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Channel.o
.PHONY : Channel.o

# target to preprocess a source file
Channel.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Channel.i
.PHONY : Channel.i

# target to generate assembly for a file
Channel.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Channel.s
.PHONY : Channel.s

# target to build an object file
Connector.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Connector.o
.PHONY : Connector.o

# target to preprocess a source file
Connector.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Connector.i
.PHONY : Connector.i

# target to generate assembly for a file
Connector.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Connector.s
.PHONY : Connector.s

# target to build an object file
EPoller.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EPoller.o
.PHONY : EPoller.o

# target to preprocess a source file
EPoller.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EPoller.i
.PHONY : EPoller.i

# target to generate assembly for a file
EPoller.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EPoller.s
.PHONY : EPoller.s

# target to build an object file
EventLoop.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoop.o
.PHONY : EventLoop.o

# target to preprocess a source file
EventLoop.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoop.i
.PHONY : EventLoop.i

# target to generate assembly for a file
EventLoop.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoop.s
.PHONY : EventLoop.s

# target to build an object file
EventLoopThread.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoopThread.o
.PHONY : EventLoopThread.o

# target to preprocess a source file
EventLoopThread.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoopThread.i
.PHONY : EventLoopThread.i

# target to generate assembly for a file
EventLoopThread.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoopThread.s
.PHONY : EventLoopThread.s

# target to build an object file
InetAddress.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/InetAddress.o
.PHONY : InetAddress.o

# target to preprocess a source file
InetAddress.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/InetAddress.i
.PHONY : InetAddress.i

# target to generate assembly for a file
InetAddress.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/InetAddress.s
.PHONY : InetAddress.s

# target to build an object file
Logger.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Logger.o
.PHONY : Logger.o

# target to preprocess a source file
Logger.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Logger.i
.PHONY : Logger.i

# target to generate assembly for a file
Logger.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Logger.s
.PHONY : Logger.s

# target to build an object file
TcpClient.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpClient.o
.PHONY : TcpClient.o

# target to preprocess a source file
TcpClient.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpClient.i
.PHONY : TcpClient.i

# target to generate assembly for a file
TcpClient.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpClient.s
.PHONY : TcpClient.s

# target to build an object file
TcpConnection.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpConnection.o
.PHONY : TcpConnection.o

# target to preprocess a source file
TcpConnection.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpConnection.i
.PHONY : TcpConnection.i

# target to generate assembly for a file
TcpConnection.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpConnection.s
.PHONY : TcpConnection.s

# target to build an object file
TcpServer.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpServer.o
.PHONY : TcpServer.o

# target to preprocess a source file
TcpServer.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpServer.i
.PHONY : TcpServer.i

# target to generate assembly for a file
TcpServer.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpServer.s
.PHONY : TcpServer.s

# target to build an object file
TcpServerSingle.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpServerSingle.o
.PHONY : TcpServerSingle.o

# target to preprocess a source file
TcpServerSingle.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpServerSingle.i
.PHONY : TcpServerSingle.i

# target to generate assembly for a file
TcpServerSingle.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TcpServerSingle.s
.PHONY : TcpServerSingle.s

# target to build an object file
ThreadPool.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/ThreadPool.o
.PHONY : ThreadPool.o

# target to preprocess a source file
ThreadPool.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/ThreadPool.i
.PHONY : ThreadPool.i

# target to generate assembly for a file
ThreadPool.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/ThreadPool.s
.PHONY : ThreadPool.s

# target to build an object file
TimerQueue.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TimerQueue.o
.PHONY : TimerQueue.o

# target to preprocess a source file
TimerQueue.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TimerQueue.i
.PHONY : TimerQueue.i

# target to generate assembly for a file
TimerQueue.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TimerQueue.s
.PHONY : TimerQueue.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... tinyev"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... Acceptor.o"
	@echo "... Acceptor.i"
	@echo "... Acceptor.s"
	@echo "... Buffer.o"
	@echo "... Buffer.i"
	@echo "... Buffer.s"
	@echo "... Channel.o"
	@echo "... Channel.i"
	@echo "... Channel.s"
	@echo "... Connector.o"
	@echo "... Connector.i"
	@echo "... Connector.s"
	@echo "... EPoller.o"
	@echo "... EPoller.i"
	@echo "... EPoller.s"
	@echo "... EventLoop.o"
	@echo "... EventLoop.i"
	@echo "... EventLoop.s"
	@echo "... EventLoopThread.o"
	@echo "... EventLoopThread.i"
	@echo "... EventLoopThread.s"
	@echo "... InetAddress.o"
	@echo "... InetAddress.i"
	@echo "... InetAddress.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... TcpClient.o"
	@echo "... TcpClient.i"
	@echo "... TcpClient.s"
	@echo "... TcpConnection.o"
	@echo "... TcpConnection.i"
	@echo "... TcpConnection.s"
	@echo "... TcpServer.o"
	@echo "... TcpServer.i"
	@echo "... TcpServer.s"
	@echo "... TcpServerSingle.o"
	@echo "... TcpServerSingle.i"
	@echo "... TcpServerSingle.s"
	@echo "... ThreadPool.o"
	@echo "... ThreadPool.i"
	@echo "... ThreadPool.s"
	@echo "... TimerQueue.o"
	@echo "... TimerQueue.i"
	@echo "... TimerQueue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

