# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/39/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/39/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ddang/library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ddang/library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/39/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ddang/library/CMakeFiles /home/ddang/library/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ddang/library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyev

# Build rule for target.
tinyev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyev
.PHONY : tinyev

# fast build rule for target.
tinyev/fast:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/build
.PHONY : tinyev/fast

Channel.o: Channel.cc.o

.PHONY : Channel.o

# target to build an object file
Channel.cc.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Channel.cc.o
.PHONY : Channel.cc.o

Channel.i: Channel.cc.i

.PHONY : Channel.i

# target to preprocess a source file
Channel.cc.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Channel.cc.i
.PHONY : Channel.cc.i

Channel.s: Channel.cc.s

.PHONY : Channel.s

# target to generate assembly for a file
Channel.cc.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Channel.cc.s
.PHONY : Channel.cc.s

EPoller.o: EPoller.cc.o

.PHONY : EPoller.o

# target to build an object file
EPoller.cc.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EPoller.cc.o
.PHONY : EPoller.cc.o

EPoller.i: EPoller.cc.i

.PHONY : EPoller.i

# target to preprocess a source file
EPoller.cc.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EPoller.cc.i
.PHONY : EPoller.cc.i

EPoller.s: EPoller.cc.s

.PHONY : EPoller.s

# target to generate assembly for a file
EPoller.cc.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EPoller.cc.s
.PHONY : EPoller.cc.s

EventLoop.o: EventLoop.cc.o

.PHONY : EventLoop.o

# target to build an object file
EventLoop.cc.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoop.cc.o
.PHONY : EventLoop.cc.o

EventLoop.i: EventLoop.cc.i

.PHONY : EventLoop.i

# target to preprocess a source file
EventLoop.cc.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoop.cc.i
.PHONY : EventLoop.cc.i

EventLoop.s: EventLoop.cc.s

.PHONY : EventLoop.s

# target to generate assembly for a file
EventLoop.cc.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoop.cc.s
.PHONY : EventLoop.cc.s

EventLoopThread.o: EventLoopThread.cc.o

.PHONY : EventLoopThread.o

# target to build an object file
EventLoopThread.cc.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoopThread.cc.o
.PHONY : EventLoopThread.cc.o

EventLoopThread.i: EventLoopThread.cc.i

.PHONY : EventLoopThread.i

# target to preprocess a source file
EventLoopThread.cc.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoopThread.cc.i
.PHONY : EventLoopThread.cc.i

EventLoopThread.s: EventLoopThread.cc.s

.PHONY : EventLoopThread.s

# target to generate assembly for a file
EventLoopThread.cc.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/EventLoopThread.cc.s
.PHONY : EventLoopThread.cc.s

Logger.o: Logger.c.o

.PHONY : Logger.o

# target to build an object file
Logger.c.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Logger.c.o
.PHONY : Logger.c.o

Logger.i: Logger.c.i

.PHONY : Logger.i

# target to preprocess a source file
Logger.c.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Logger.c.i
.PHONY : Logger.c.i

Logger.s: Logger.c.s

.PHONY : Logger.s

# target to generate assembly for a file
Logger.c.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/Logger.c.s
.PHONY : Logger.c.s

ThreadPool.o: ThreadPool.cc.o

.PHONY : ThreadPool.o

# target to build an object file
ThreadPool.cc.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/ThreadPool.cc.o
.PHONY : ThreadPool.cc.o

ThreadPool.i: ThreadPool.cc.i

.PHONY : ThreadPool.i

# target to preprocess a source file
ThreadPool.cc.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/ThreadPool.cc.i
.PHONY : ThreadPool.cc.i

ThreadPool.s: ThreadPool.cc.s

.PHONY : ThreadPool.s

# target to generate assembly for a file
ThreadPool.cc.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/ThreadPool.cc.s
.PHONY : ThreadPool.cc.s

TimerQueue.o: TimerQueue.cc.o

.PHONY : TimerQueue.o

# target to build an object file
TimerQueue.cc.o:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TimerQueue.cc.o
.PHONY : TimerQueue.cc.o

TimerQueue.i: TimerQueue.cc.i

.PHONY : TimerQueue.i

# target to preprocess a source file
TimerQueue.cc.i:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TimerQueue.cc.i
.PHONY : TimerQueue.cc.i

TimerQueue.s: TimerQueue.cc.s

.PHONY : TimerQueue.s

# target to generate assembly for a file
TimerQueue.cc.s:
	$(MAKE) -f CMakeFiles/tinyev.dir/build.make CMakeFiles/tinyev.dir/TimerQueue.cc.s
.PHONY : TimerQueue.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... tinyev"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... Channel.o"
	@echo "... Channel.i"
	@echo "... Channel.s"
	@echo "... EPoller.o"
	@echo "... EPoller.i"
	@echo "... EPoller.s"
	@echo "... EventLoop.o"
	@echo "... EventLoop.i"
	@echo "... EventLoop.s"
	@echo "... EventLoopThread.o"
	@echo "... EventLoopThread.i"
	@echo "... EventLoopThread.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... ThreadPool.o"
	@echo "... ThreadPool.i"
	@echo "... ThreadPool.s"
	@echo "... TimerQueue.o"
	@echo "... TimerQueue.i"
	@echo "... TimerQueue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

